### ISSUE TITLE
error when running the examples

### ISSUE THREAD

**Issue by lzhangUT** [senresearch/BulkLMM.jl#85]
Hi 
I am trying to use the package starting with your example here.
Here are the two errors I encountered.
1. things worked fine before this code, and the results are the same as shown in the README
julia> lod_thresholds = get_thrsholds(single_results_perms.L_perms, [0.90, 0.95]);
ERROR: UndefVarError: `get_thrsholds` not defined
Stacktrace:
 [1] top-level scope
   @ REPL[25]:1
  
I tried to skip this one as it was just getting the threshold value, I can set a threshold value by using lod_thresholds= 3.5 for example.

2. then I ran into another problem when trying to use the package for plotting: BigRiverQTLPlots
julia> using BigRiverQTLPlots
ERROR: ArgumentError: Package BigRiverQTLPlots not found in current path.
- Run `import Pkg; Pkg.add("BigRiverQTLPlots")` to install the BigRiverQTLPlots package.
Stacktrace:
 [1] macro expansion
   @ .\loading.jl:1630 [inlined]
 [2] macro expansion
   @ .\lock.jl:267 [inlined]
 [3] require(into::Module, mod::Symbol)
   @ Base .\loading.jl:1611

3. well I thought it was because it was not added, then I did 
julia> import Pkg; Pkg.add("BigRiverQTLPlots")
ERROR: The following package names could not be resolved:
 * BigRiverQTLPlots (not found in project, manifest or registry)
Stacktrace:
  [1] pkgerror(msg::String)
    @ Pkg.Types C:\Users\Li Zhang\AppData\Local\Programs\Julia-1.9.2\share\julia\stdlib\v1.9\Pkg\src\Types.jl:69
  [2] ensure_resolved(ctx::Pkg.Types.Context, manifest::Pkg.Types.Manifest, pkgs::Vector{Pkg.Types.PackageSpec}; registry::Bool)
    @ Pkg.Types C:\Users\Li Zhang\AppData\Local\Programs\Julia-1.9.2\share\julia\stdlib\v1.9\Pkg\src\Types.jl:1003
  [3] ensure_resolved
    @ C:\Users\Li Zhang\AppData\Local\Programs\Julia-1.9.2\share\julia\stdlib\v1.9\Pkg\src\Types.jl:954 [inlined]
  [4] add(ctx::Pkg.Types.Context, pkgs::Vector{Pkg.Types.PackageSpec}; preserve::Pkg.Types.PreserveLevel, platform::Base.BinaryPlatforms.Platform, kwargs::Base.Pairs{Symbol, Base.TTY, Tuple{Symbol}, NamedTuple{(:io,), Tuple{Base.TTY}}})
    @ Pkg.API C:\Users\Li Zhang\AppData\Local\Programs\Julia-1.9.2\share\julia\stdlib\v1.9\Pkg\src\API.jl:264
  [5] add(pkgs::Vector{Pkg.Types.PackageSpec}; io::Base.TTY, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Pkg.API C:\Users\Li Zhang\AppData\Local\Programs\Julia-1.9.2\share\julia\stdlib\v1.9\Pkg\src\API.jl:156
  [6] add(pkgs::Vector{Pkg.Types.PackageSpec})
    @ Pkg.API C:\Users\Li Zhang\AppData\Local\Programs\Julia-1.9.2\share\julia\stdlib\v1.9\Pkg\src\API.jl:145
  [7] #add#25
    @ C:\Users\Li Zhang\AppData\Local\Programs\Julia-1.9.2\share\julia\stdlib\v1.9\Pkg\src\API.jl:144 [inlined]
  [8] add
    @ C:\Users\Li Zhang\AppData\Local\Programs\Julia-1.9.2\share\julia\stdlib\v1.9\Pkg\src\API.jl:144 [inlined]
  [9] #add#24
    @ C:\Users\Li Zhang\AppData\Local\Programs\Julia-1.9.2\share\julia\stdlib\v1.9\Pkg\src\API.jl:143 [inlined]
 [10] add(pkg::String)
    @ Pkg.API C:\Users\Li Zhang\AppData\Local\Programs\Julia-1.9.2\share\julia\stdlib\v1.9\Pkg\src\API.jl:143
 [11] top-level scope
    @ REPL[37]:1

I also tried :
using Pkg
Pkg.add("BigRiverQTLPlots")
following the github https://github.com/senresearch/BigRiverQTLPlots.jl
it is the same error.

Any help would be appreciated

**Comment by GregFa** [comment]
> 1. things worked fine before this code below, and the results before this code are the same as shown in the README 
julia> lod_thresholds = get_thrsholds(single_results_perms.L_perms, [0.90, 0.95]);
ERROR: UndefVarError: get_thrsholds not defined
Stacktrace:
[1] top-level scope
@ REPL[25]:1
 
I believe there is a typo in the README; the function is get_threshold with an "e". I will correct the typo; thank you for pointing it out.

> 2. then I ran into another problem when trying to use the package for plotting: BigRiverQTLPlots
julia> using BigRiverQTLPlots
ERROR: ArgumentError: Package BigRiverQTLPlots not found in current path.
Run import Pkg; Pkg.add("BigRiverQTLPlots") to install the BigRiverQTLPlots package.
Stacktrace: 
[1] macro expansion
@ .\loading.jl:1630 [inlined]
[2] macro expansion
@ .\lock.jl:267 [inlined]
[3] require(into::Module, mod::Symbol)
@ Base .\loading.jl:1611
> 3. well I thought it was because it was not added, then I did
julia> import Pkg; Pkg.add("BigRiverQTLPlots")
ERROR: The following package names could not be resolved:
 
Indeed, the package BigRiverQTLPlots needs to be added, but it is not yet officially registered. Actually, it should be registered this week. Meanwhile, you can still add the package directly using the GitHub address of the package, such as:
```julia
julia> using Pkg
julia> Pkg.add("https://github.com/senresearch/BigRiverQTLPlots.jl.git")
```
We have made a minor change compared to the example in BulkLMM.

- Before:
```julia
plot_QTL(
         single_results_perms, 
         gInfo, 
         thresholds = [0.90, 0.95],
         legend = true,
         label = "BulkLMM.jl",
         title = "Single trait $traitName LOD scores"
)
```
- Now:
```julia
plot_QTL(
         single_results_perms, 
         gInfo, 
         significance = [0.10, 0.05],  # changed here 
         legend = true,
         label = "BulkLMM.jl",
         title = "Single trait $traitName LOD scores"
)
```
You can also check examples in [https://github.com/senresearch/BigRiverQTLPlots.jl/tree/main/example](https://github.com/senresearch/BigRiverQTLPlots.jl/tree/main/example)
